### ISSUE TITLE
Feature Request: Open links in seperate tabs

### ISSUE THREAD

**Issue by Nivdy** [gamingdoom/datcord#65] opened 2024-06-13 01:56 UTC
whenever I click a link, it will bring me to the website in the same app as datcord, and as such, I won't be able to return to datcord, and will be stuck until I force close and reopen datcord. opening through another tab or through my firefox installation would solve this by not leaving the discord client.

**Comment by gamingdoom** [comment] 2024-06-13 02:00
Duplicate of #60. There is a workaround on that issue.

**Closed by gamingdoom** 2024-06-13 02:00 UTC
