### ISSUE TITLE
Links open in app, not default browser since 0.5.0

### ISSUE THREAD

**Issue by TylerLaBree** [gamingdoom/datcord#60] opened 2024-02-20 16:09 UTC
I'm on the 0.5.1 flatpak, and when I click links in the app, they open in datcord, replacing discord. I can use my mouse's back button to return to discord. When I middle click a link, it opens in a new tab in datcord.

It appears packaging as a flatpak might have broken the feature requested in https://github.com/gamingdoom/datcord/issues/22

**Comment by gamingdoom** [comment] 2024-02-20 21:30
This is a regression that got introduced in 0.5.0. It will be fixed for 0.5.2

**Comment by Neocraft1293** [comment] 2024-04-06 15:17
Hey there,
I'm also experiencing the same issue with the Datcord app (version datcord-bin-0.5.1-1) on Arch Linux. I've just finished installing it, and as soon as I tried clicking on one links within the app, they open in Datcord instead of my default browser.

**Comment by gamingdoom** [comment] 2024-05-10 19:18
Sorry for the long delay, I have been busy with personal things. This should be fixed soon™

**Comment by gamingdoom** [comment] 2024-06-12 23:23
Hello everyone,
It seems that if you started using Datcord after 0.5.0, you will need to install the open-in-default-browser extension manually by downloading it and then dragging it onto Datcord:
[open-in-default-browser@sanghai.org.zip](https://github.com/user-attachments/files/15811902/open-in-default-browser%40sanghai.org.zip) (change the .zip to .xpi, Github doesnt let me upload .xpi files)

I don't think it will automatically fix if you upgrade your Datcord version since it seems to only autoinstall extensions with new profiles.

**Comment by gamingdoom** [comment] 2024-06-13 05:13
Fixed with 0.5.2

**Closed by gamingdoom** 2024-06-13 05:13 UTC
Labels: bug
