### ISSUE TITLE
Screen sharing support

### ISSUE THREAD

**Issue by nose-gnome** [gamingdoom/datcord#37] opened 2022-12-01 19:17 UTC
If you press the screen share button, nothing happens.  It would be great if you could add screen sharing support

**Comment by nose-gnome** [comment] 2022-12-01 19:20
After re-starting Datcord  screen sharing started working again

**Comment by nose-gnome** [comment] 2022-12-02 17:30
It is happening repeatedly.  Seems to be an issue with the notification appearing.  I've found that if you open Discord in a new tab, it works again

**Comment by gamingdoom** [comment] 2023-01-24 02:14
This issue and issue #37 (they are the same issue) have been fixed in the latest commit to unstable and will a new version of Datcord will be released when everything is done building. The issue was caused by the screen sharing prompt trying to find the screen sharing icon in the url bar but the url bar was removed. I hid the url bar by making it 0 pixels tall which means that everything still exists and the screen sharing prompt can find the screen sharing button.

**Closed by gamingdoom** 2023-01-24 02:14 UTC
Labels: bug
